version: '3.4'

services:
  restapi:
    image: ${DOCKER_REGISTRY-}restapi
    build:
      context: .
      dockerfile: RestApi/Dockerfile
    depends_on: 
      - mssql
    networks:
      - backend
    volumes:
      - ../csv_data/:/initdata

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=LubiePlacki1234
      - MSSQL_PID=Express
    networks:
      - backend

networks:
  backend: